#!/usr/bin/bash

wd=/media/store/Tmp/blocklist
url=https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist
for i in {0..2}; do
	curl -so $wd/domains$i.in $url/Ultimate.Hosts.Blacklist/master/domains/domains$i.list
done

## Backup current /etc/hosts
cp -f /etc/hosts $wd/hosts.old;

## Merge lists to workfile
cat $wd/domains0.in $wd/domains1.in $wd/domains2.in $wd/custom.in > $wd/wrk.cp1;

## clean up any duplicates
awk '!x[$0]++' $wd/wrk.cp1 > $wd/wrk.cp2;

## Stack 9 hosts on each line
awk 'ORS=NR%9?" ":"\n"' $wd/wrk.cp2 > $wd/wrk.cp3;

## Reinsert ip on each line
sed -i 's/^/0.0.0.0 /' $wd/wrk.cp3;

## Glue all
cat $wd/localhost.in $wd/wrk.cp3 > $wd/hosts.out;

## Copy new hosts to /etc
mv $wd/hosts.out /etc/hosts;

## Cleanup all work copies
rm $wd/wrk.* ;
