#!/usr/bin/sh

token="$(cat $HOME/.config/creds/freedns)"

# Sync FreeDNS
/usr/bin/curl -k -s "$token" | sed 's/^ERROR: Address //' |
 while read dns; do
    dunstify -a info2 "⤒ Freedns" "<a href=\"https://freedns.afraid.org\"></a>\n$dns" -t 60000
done
