#!/usr/bin/sh

/usr/bin/curl -k -s http://freedns.afraid.org/dynamic/update.php?S0ZuZnpCTVpvWTJWclgybG5DcHI6NzU0OTg0MQ== |
 sed 's/^ERROR: Address //' |
 while read dns; do
	dunstify -a info "Freedns" "<a href=\"https://freedns.afraid.org\"></a>\n$dns" -t 60000
done
