#!/bin/sh

/usr/bin/curl -k -s http://freedns.afraid.org/dynamic/update.php?S0ZuZnpCTVpvWTJWclgybG5DcHI6NzU0OTg0MQ== |
 sed 's/^ERROR: Address //' |
 while read out; do
	dunstify -a info "Freedns" "\n<a href=\"https://freedns.afraid.org\"></a>$out" -t 60000
done
