#!/bin/sh

# Check update packages
res="$(xbps-install -nuM | wc -l)"
[ $res != 0 ] && dunstify -a info -r 1169 "Update xbps" "\n$res - New package(s)"

# Daily forunes
dunstify -r 6718 "Daily Fortune" "\n$(/usr/bin/fortune)" -t 60000 -u low

# Clean bash history
/usr/local/bin/histcleanup > /tmp/hist.clean
mv -f /tmp/hist.clean /home/userx/.bash_history
dunstify "Bash" "\nHistory	cleaned" -t 30000 -u low
